# Generated by Django 5.0.1 on 2024-04-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0007_alter_employee_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='fullName',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombre Completo'),
        ),
    ]
