# Generated by Django 5.0.1 on 2024-04-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0008_employee_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Foto'),
        ),
    ]
