# Generated by Django 5.0.1 on 2024-01-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dep',
            name='name',
            field=models.CharField(blank=True, max_length=60, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='dep',
            name='shortName',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nombre Corto'),
        ),
    ]
