# Generated by Django 5.0.1 on 2024-04-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='cantidad',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
