# Generated by Django 5.0.1 on 2024-01-06 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0002_alter_dep_name_alter_dep_shortname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dep',
            options={'managed': True, 'ordering': ['name'], 'verbose_name': 'departament', 'verbose_name_plural': 'departaments'},
        ),
        migrations.AlterUniqueTogether(
            name='dep',
            unique_together={('name', 'shortName')},
        ),
        migrations.AlterModelTable(
            name='dep',
            table='',
        ),
    ]
