# Generated by Django 5.0.1 on 2024-01-05 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dep', '0002_alter_dep_name_alter_dep_shortname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=60, verbose_name='Nombre(s)')),
                ('lastName', models.EmailField(max_length=60, verbose_name='Apellido(s)')),
                ('email', models.CharField(max_length=50, unique=True, verbose_name='Email')),
                ('job', models.CharField(choices=[('0', 'contador'), ('1', 'administrador'), ('2', 'economista'), ('3', 'ingeniero'), ('4', 'otro')], max_length=1, verbose_name='Puesto')),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dep.dep')),
            ],
        ),
    ]
