# Generated by Django 5.0.1 on 2024-01-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='lastName',
            field=models.CharField(max_length=60, verbose_name='Apellido(s)'),
        ),
    ]
