# Generated by Django 5.0.1 on 2024-01-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_alter_empleado_email_alter_empleado_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50, verbose_name='Habilidad')),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skills',
                'db_table': '',
                'ordering': ['skill'],
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'managed': True, 'ordering': ['firstName', 'lastName', 'email'], 'verbose_name': 'employee', 'verbose_name_plural': 'employees'},
        ),
        migrations.AlterUniqueTogether(
            name='empleado',
            unique_together={('email',)},
        ),
        migrations.AlterModelTable(
            name='empleado',
            table='',
        ),
    ]
