# Generated by Django 5.0.1 on 2024-01-18 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0005_rename_empleado_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': True, 'ordering': ['id', 'firstName', 'lastName', 'email', 'dep'], 'verbose_name': 'employee', 'verbose_name_plural': 'employees'},
        ),
    ]
