# Generated by Django 5.0.1 on 2024-01-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0006_alter_employee_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job',
            field=models.CharField(choices=[('0', 'Ingeniero'), ('1', 'Practicante'), ('2', 'Administrador'), ('3', 'Contador'), ('4', 'RH'), ('5', 'Cliente')], max_length=1, verbose_name='Puesto'),
        ),
    ]
