# Generated by Django 5.0.1 on 2024-04-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0009_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='empPhoto', verbose_name='Foto'),
        ),
    ]
